package org.antlr.codebuff.gui;

import javax.swing.*;
import java.awt.*;

public class BuffScope {
	private JSplitPane codeAndResultsSplitPane;
	private JSplitPane origVsBuffedSplitPane;
	protected JPanel overallPanel;
	protected JTextArea analysisConsole;
	protected JTextPane origTextPane;
	protected JTextPane formattedTextPane;

	public JTextArea getAnalysisConsole() {
		return analysisConsole;
	}

	public JTextPane getFormattedTextPane() {
		return formattedTextPane;
	}

	public JTextPane getOrigTextPane() {
		return origTextPane;
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		overallPanel = new JPanel();
		overallPanel.setLayout(new BorderLayout(0, 0));
		overallPanel.setPreferredSize(new Dimension(800, 800));
		codeAndResultsSplitPane = new JSplitPane();
		codeAndResultsSplitPane.setContinuousLayout(true);
		codeAndResultsSplitPane.setOrientation(0);
		codeAndResultsSplitPane.setResizeWeight(0.5);
		overallPanel.add(codeAndResultsSplitPane, BorderLayout.CENTER);
		origVsBuffedSplitPane = new JSplitPane();
		origVsBuffedSplitPane.setContinuousLayout(true);
		origVsBuffedSplitPane.setDividerLocation(252);
		codeAndResultsSplitPane.setLeftComponent(origVsBuffedSplitPane);
		formattedTextPane = new JTextPane();
		formattedTextPane.setEditable(false);
		formattedTextPane.setMinimumSize(new Dimension(200, 100));
		formattedTextPane.setText("original");
		origVsBuffedSplitPane.setRightComponent(formattedTextPane);
		origTextPane = new JTextPane();
		origTextPane.setEditable(false);
		origTextPane.setMinimumSize(new Dimension(200, 100));
		origTextPane.setText("Buffed text");
		origVsBuffedSplitPane.setLeftComponent(origTextPane);
		analysisConsole = new JTextArea();
		analysisConsole.setEditable(false);
		analysisConsole.setPreferredSize(new Dimension(800, 200));
		codeAndResultsSplitPane.setRightComponent(analysisConsole);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return overallPanel;
	}
}
